# Generated by Django 5.2.4 on 2025-07-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='free_analysis_count',
            field=models.IntegerField(default=10, verbose_name='Free Analysis/Summarization Count'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_pro',
            field=models.BooleanField(default=False, verbose_name='Is Pro User'),
        ),
    ]
