# Generated by Django 5.2.4 on 2025-07-11 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_input', models.TextField(verbose_name='Input Text')),
                ('analysis_result', models.JSONField(verbose_name='Analysis Result')),
                ('analysis_source', models.CharField(choices=[('gemini', 'Gemini API'), ('internal', 'Internal Model')], default='gemini', max_length=20, verbose_name='Analysis Source')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_history', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Sentiment Analysis History',
                'verbose_name_plural': 'Sentiment Analysis Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SummarizationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_input', models.TextField(verbose_name='Input Text')),
                ('summarized_text', models.TextField(verbose_name='Summarized Text')),
                ('summarization_source', models.CharField(choices=[('gemini', 'Gemini API'), ('internal', 'Internal Model')], default='gemini', max_length=20, verbose_name='Summarization Source')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summarization_history', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Summarization History',
                'verbose_name_plural': 'Summarization Histories',
                'ordering': ['-timestamp'],
            },
        ),
    ]
