# Generated by Django 5.2.4 on 2025-07-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysishistory',
            name='analysis_type',
            field=models.CharField(default='general_sentiment', max_length=50),
        ),
        migrations.AddField(
            model_name='summarizationhistory',
            name='max_words_summarization',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='analysishistory',
            name='analysis_source',
            field=models.CharField(choices=[('gemini', 'Gemini API'), ('internal', 'Internal Model'), ('mock', 'Mock Processor')], default='gemini', max_length=20, verbose_name='Analysis Source'),
        ),
        migrations.AlterField(
            model_name='summarizationhistory',
            name='summarization_source',
            field=models.CharField(choices=[('openai', 'OpenAI API'), ('gemini', 'Gemini API'), ('internal', 'Internal Model'), ('mock', 'Mock Processor')], default='gemini', max_length=20, verbose_name='Summarization Source'),
        ),
    ]
